apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
  labels:
    prometheus: prometheus-monitoring
    k8s-app: monitoring
spec:
  jobLabel: monitoring
  selector:
    matchLabels:
      k8s-app: user-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: http-metrics
    interval: 30s