apiVersion: extensions/v1beta1
kind: ingressmetadata:
  name: base-ingress
spec:
  tls:
  - hosts:
    - "*.doxsey.net"
    secretName: doxsey-net-tls
  rules:
  - host: www.doxsey.net
    http:
      paths: /
      backend:
        serviceName: doxsey-www
        servicePort: 9002
---
apiVersion: v1
kind: Pod
metadata:
  name: ingress
  labels:
    app: ingress
spec:
  containers:
    - name: ingress
      image: jtheiss19/test20
      ports:
      - containerPort: 4000
      volumeMounts:
      - name: config-volume
        mountPath: /root/.kube/
  volumes:
    - name: config-volume
      configMap:
        name: ingress