apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name -}}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      {{- range $app := .Values.apps }}
      - name: {{ .$app.name }}
        image: {{ $app.imageurl }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        {{- range $port := $app.ports }}
        - containerPort: {{$port -}}
        {{- end }}
      {{ end }}