{{- range $app := .Values.apps }}
---
# Istio - Gateway Addon
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $app.name }}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  {{- range $port := $app.ports }}
  - port:
      number: {{ $port }}
      name: http
      protocol: HTTP
    hosts:
    - "*"
  {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $app.name }}-vs
spec:
  hosts:
  - "*"
  gateways:
  - {{ $app.name }}-gateway
  http:
  - match:
  {{- range $endpoint := $app.endpoints }}
    - uri:
        exact: {{ $endpoint }}
  {{- end }}
    route:
    - destination:
        host: {{ $app.name }}
        port:
          number: {{ $app.serviceport }}
{{ end }}