{{- range $app := .Values.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name }}
spec:
  ports:
  {{ range $port := $app.ports }}
    - port: {{ $port }}
      name: {{"http-"}}{{- $port }}
  {{ end }}
  selector:
    app: {{ $app.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $app.name }}-svcact
  labels:
    account: {{ $app.name }}
{{ end }}